# Generated by Django 6.0.6 on 2026-06-12 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('condition', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clothes/')),
                ('status', models.CharField(default='Available', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
